/* This file is auto-generated by tools/generate_instructions.py.
 * Do not edit by hand. Regenerate after changes to the public header
 * include/sirit/sirit.h or to the SPIR-V grammar files
 * (externals/SPIRV-Headers/include/spirv/unified1/spirv.core.grammar.json
 * and the bundled extinst.*.grammar.json files).
 */

#include <spirv/unified1/AMD_gcn_shader.h>
#include <spirv/unified1/AMD_shader_explicit_vertex_parameter.h>
#include <spirv/unified1/AMD_shader_trinary_minmax.h>
#include <spirv/unified1/GLSL.std.450.h>
#include <spirv/unified1/NonSemanticDebugPrintf.h>

#include "sirit/sirit.h"

#include "stream.h"

namespace Sirit {

Id Module::TypeVoid() {
    declarations->Reserve(2);
    return *declarations << OpId{spv::Op::OpTypeVoid} << EndOp{};
}

Id Module::TypeBool() {
    declarations->Reserve(2);
    return *declarations << OpId{spv::Op::OpTypeBool} << EndOp{};
}

Id Module::TypeInt(int width, bool is_signed) {
    declarations->Reserve(4);
    return *declarations << OpId{spv::Op::OpTypeInt} << width << is_signed << EndOp{};
}

Id Module::TypeFloat(int width) {
    declarations->Reserve(3);
    return *declarations << OpId{spv::Op::OpTypeFloat} << width << EndOp{};
}

Id Module::TypeVector(Id component_type, int component_count) {
    declarations->Reserve(4);
    return *declarations << OpId{spv::Op::OpTypeVector} << component_type << component_count << EndOp{};
}

Id Module::TypeMatrix(Id column_type, int column_count) {
    declarations->Reserve(4);
    return *declarations << OpId{spv::Op::OpTypeMatrix} << column_type << column_count << EndOp{};
}

Id Module::TypeImage(Id sampled_type, spv::Dim dim, int depth, bool arrayed, bool ms, int sampled, spv::ImageFormat image_format, std::optional<spv::AccessQualifier> access_qualifier) {
    declarations->Reserve(9 + (access_qualifier.has_value() ? 1 : 0));
    return *declarations << OpId{spv::Op::OpTypeImage} << sampled_type << dim << depth << arrayed << ms << sampled << image_format << access_qualifier << EndOp{};
}

Id Module::TypeSampler() {
    declarations->Reserve(2);
    return *declarations << OpId{spv::Op::OpTypeSampler} << EndOp{};
}

Id Module::TypeSampledImage(Id image_type) {
    declarations->Reserve(3);
    return *declarations << OpId{spv::Op::OpTypeSampledImage} << image_type << EndOp{};
}

Id Module::TypeArray(Id element_type, Id length) {
    declarations->Reserve(4);
    return *declarations << OpId{spv::Op::OpTypeArray} << element_type << length << EndOp{};
}

Id Module::TypeRuntimeArray(Id element_type) {
    declarations->Reserve(3);
    return *declarations << OpId{spv::Op::OpTypeRuntimeArray} << element_type << EndOp{};
}

Id Module::TypeStruct(std::span<const Id> members) {
    declarations->Reserve(2 + members.size());
    return *declarations << OpId{spv::Op::OpTypeStruct} << members << EndOp{};
}

Id Module::TypeOpaque(std::string_view name) {
    declarations->Reserve(2 + WordsInString(name));
    return *declarations << OpId{spv::Op::OpTypeOpaque} << name << EndOp{};
}

Id Module::TypePointer(spv::StorageClass storage_class, Id type) {
    declarations->Reserve(4);
    return *declarations << OpId{spv::Op::OpTypePointer} << storage_class << type << EndOp{};
}

Id Module::TypeFunction(Id return_type, std::span<const Id> arguments) {
    declarations->Reserve(3 + arguments.size());
    return *declarations << OpId{spv::Op::OpTypeFunction} << return_type << arguments << EndOp{};
}

Id Module::TypeEvent() {
    declarations->Reserve(2);
    return *declarations << OpId{spv::Op::OpTypeEvent} << EndOp{};
}

Id Module::TypeDeviceEvent() {
    declarations->Reserve(2);
    return *declarations << OpId{spv::Op::OpTypeDeviceEvent} << EndOp{};
}

Id Module::TypeReserveId() {
    declarations->Reserve(2);
    return *declarations << OpId{spv::Op::OpTypeReserveId} << EndOp{};
}

Id Module::TypeQueue() {
    declarations->Reserve(2);
    return *declarations << OpId{spv::Op::OpTypeQueue} << EndOp{};
}

Id Module::TypePipe(spv::AccessQualifier access_qualifier) {
    declarations->Reserve(3);
    return *declarations << OpId{spv::Op::OpTypePipe} << access_qualifier << EndOp{};
}

Id Module::ConstantTrue(Id result_type) {
    declarations->Reserve(3);
    return *declarations << OpId{spv::Op::OpConstantTrue, result_type} << EndOp{};
}

Id Module::ConstantFalse(Id result_type) {
    declarations->Reserve(3);
    return *declarations << OpId{spv::Op::OpConstantFalse, result_type} << EndOp{};
}

Id Module::Constant(Id result_type, const Literal& literal) {
    declarations->Reserve(5);
    return *declarations << OpId{spv::Op::OpConstant, result_type} << literal << EndOp{};
}

Id Module::ConstantComposite(Id result_type, std::span<const Id> constituents) {
    declarations->Reserve(3 + constituents.size());
    return *declarations << OpId{spv::Op::OpConstantComposite, result_type} << constituents << EndOp{};
}

Id Module::ConstantSampler(Id result_type, spv::SamplerAddressingMode addressing_mode, bool normalized, spv::SamplerFilterMode filter_mode) {
    declarations->Reserve(6);
    return *declarations << OpId{spv::Op::OpConstantSampler, result_type} << addressing_mode << normalized << filter_mode << EndOp{};
}

Id Module::ConstantNull(Id result_type) {
    declarations->Reserve(3);
    return *declarations << OpId{spv::Op::OpConstantNull, result_type} << EndOp{};
}

Id Module::OpFunction(Id result_type, spv::FunctionControlMask function_control, Id function_type) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFunction, result_type} << function_control << function_type << EndOp{};
}

void Module::OpFunctionEnd() {
    code->Reserve(1);
    *code << spv::Op::OpFunctionEnd << EndOp{};
}

Id Module::OpFunctionCall(Id result_type, Id function, std::span<const Id> arguments) {
    code->Reserve(4 + arguments.size());
    return *code << OpId{spv::Op::OpFunctionCall, result_type} << function << arguments << EndOp{};
}

Id Module::OpFunctionParameter(Id result_type) {
    code->Reserve(3);
    return *code << OpId{spv::Op::OpFunctionParameter, result_type} << EndOp{};
}

Id Module::OpPhi(Id result_type, std::span<const Id> operands) {
    code->Reserve(3 + operands.size());
    return *code << OpId{spv::Op::OpPhi, result_type} << operands << EndOp{};
}

Id Module::OpLoopMerge(Id merge_block, Id continue_target, spv::LoopControlMask loop_control, std::span<const Id> literals) {
    code->Reserve(4 + literals.size());
    return *code << spv::Op::OpLoopMerge << merge_block << continue_target << loop_control << literals << EndOp{};
}

Id Module::OpSelectionMerge(Id merge_block, spv::SelectionControlMask selection_control) {
    code->Reserve(3);
    return *code << spv::Op::OpSelectionMerge << merge_block << selection_control << EndOp{};
}

Id Module::OpBranch(Id target_label) {
    code->Reserve(2);
    return *code << spv::Op::OpBranch << target_label << EndOp{};
}

void Module::OpReturn() {
    code->Reserve(1);
    *code << spv::Op::OpReturn << EndOp{};
}

void Module::OpUnreachable() {
    code->Reserve(1);
    *code << spv::Op::OpUnreachable << EndOp{};
}

Id Module::OpReturnValue(Id value) {
    code->Reserve(2);
    return *code << spv::Op::OpReturnValue << value << EndOp{};
}

void Module::OpKill() {
    code->Reserve(1);
    *code << spv::Op::OpKill << EndOp{};
}

void Module::OpDemoteToHelperInvocation() {
    code->Reserve(1);
    *code << spv::Op::OpDemoteToHelperInvocation << EndOp{};
}

void Module::OpTerminateInvocation() {
    code->Reserve(1);
    *code << spv::Op::OpTerminateInvocation << EndOp{};
}

Id Module::String(std::string_view string) {
    debug->Reserve(2 + WordsInString(string));
    return *debug << OpId{spv::Op::OpString} << string << EndOp{};
}

Id Module::OpLine(Id file, Literal line, Literal column) {
    debug->Reserve(4);
    return *debug << spv::Op::OpLine << file << line << column << EndOp{};
}

Id Module::OpImageTexelPointer(Id result_type, Id image, Id coordinate, Id sample) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpImageTexelPointer, result_type} << image << coordinate << sample << EndOp{};
}

Id Module::OpLoad(Id result_type, Id pointer, std::optional<spv::MemoryAccessMask> memory_access) {
    code->Reserve(4 + (memory_access.has_value() ? 1 : 0));
    return *code << OpId{spv::Op::OpLoad, result_type} << pointer << memory_access << EndOp{};
}

Id Module::OpStore(Id pointer, Id object, std::optional<spv::MemoryAccessMask> memory_access) {
    code->Reserve(3 + (memory_access.has_value() ? 1 : 0));
    return *code << spv::Op::OpStore << pointer << object << memory_access << EndOp{};
}

Id Module::OpAccessChain(Id result_type, Id base, std::span<const Id> indexes) {
    code->Reserve(4 + indexes.size());
    return *code << OpId{spv::Op::OpAccessChain, result_type} << base << indexes << EndOp{};
}

Id Module::OpVectorExtractDynamic(Id result_type, Id vector, Id index) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpVectorExtractDynamic, result_type} << vector << index << EndOp{};
}

Id Module::OpVectorInsertDynamic(Id result_type, Id vector, Id component, Id index) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpVectorInsertDynamic, result_type} << vector << component << index << EndOp{};
}

Id Module::OpVectorShuffle(Id result_type, Id vector_1, Id vector_2, std::span<const Literal> components) {
    code->Reserve(5 + components.size());
    return *code << OpId{spv::Op::OpVectorShuffle, result_type} << vector_1 << vector_2 << components << EndOp{};
}

Id Module::OpCompositeInsert(Id result_type, Id object, Id composite, std::span<const Literal> indexes) {
    code->Reserve(5 + indexes.size());
    return *code << OpId{spv::Op::OpCompositeInsert, result_type} << object << composite << indexes << EndOp{};
}

Id Module::OpCompositeExtract(Id result_type, Id composite, std::span<const Literal> indexes) {
    code->Reserve(4 + indexes.size());
    return *code << OpId{spv::Op::OpCompositeExtract, result_type} << composite << indexes << EndOp{};
}

Id Module::OpCompositeConstruct(Id result_type, std::span<const Id> ids) {
    code->Reserve(3 + ids.size());
    return *code << OpId{spv::Op::OpCompositeConstruct, result_type} << ids << EndOp{};
}

Id Module::Decorate(Id target, spv::Decoration decoration, std::span<const Literal> literals) {
    annotations->Reserve(3 + literals.size());
    return *annotations << spv::Op::OpDecorate << target << decoration << literals << EndOp{};
}

Id Module::MemberDecorate(Id structure_type, Literal member, spv::Decoration decoration, std::span<const Literal> literals) {
    annotations->Reserve(4 + literals.size());
    return *annotations << spv::Op::OpMemberDecorate << structure_type << member << decoration << literals << EndOp{};
}

Id Module::OpUndef(Id result_type) {
    code->Reserve(3);
    return *code << OpId{spv::Op::OpUndef, result_type} << EndOp{};
}

void Module::OpEmitVertex() {
    code->Reserve(1);
    *code << spv::Op::OpEmitVertex << EndOp{};
}

void Module::OpEndPrimitive() {
    code->Reserve(1);
    *code << spv::Op::OpEndPrimitive << EndOp{};
}

void Module::OpEmitStreamVertex(Id stream) {
    code->Reserve(2);
    *code << spv::Op::OpEmitStreamVertex << stream << EndOp{};
}

void Module::OpEndStreamPrimitive(Id stream) {
    code->Reserve(2);
    *code << spv::Op::OpEndStreamPrimitive << stream << EndOp{};
}

Id Module::OpControlBarrier(Id execution, Id memory, Id semantics) {
    code->Reserve(4);
    return *code << spv::Op::OpControlBarrier << execution << memory << semantics << EndOp{};
}

Id Module::OpMemoryBarrier(Id scope, Id semantics) {
    code->Reserve(3);
    return *code << spv::Op::OpMemoryBarrier << scope << semantics << EndOp{};
}

Id Module::OpAny(Id result_type, Id vector) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpAny, result_type} << vector << EndOp{};
}

Id Module::OpAll(Id result_type, Id vector) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpAll, result_type} << vector << EndOp{};
}

Id Module::OpIsNan(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpIsNan, result_type} << operand << EndOp{};
}

Id Module::OpIsInf(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpIsInf, result_type} << operand << EndOp{};
}

Id Module::OpLogicalEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpLogicalEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpLogicalNotEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpLogicalNotEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpLogicalOr(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpLogicalOr, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpLogicalAnd(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpLogicalAnd, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpLogicalNot(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpLogicalNot, result_type} << operand << EndOp{};
}

Id Module::OpSelect(Id result_type, Id condition, Id operand_1, Id operand_2) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpSelect, result_type} << condition << operand_1 << operand_2 << EndOp{};
}

Id Module::OpIEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpIEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpINotEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpINotEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpUGreaterThan(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpUGreaterThan, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpSGreaterThan(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpSGreaterThan, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpUGreaterThanEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpUGreaterThanEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpSGreaterThanEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpSGreaterThanEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpULessThan(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpULessThan, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpSLessThan(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpSLessThan, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpULessThanEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpULessThanEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpSLessThanEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpSLessThanEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFOrdEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFOrdEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFUnordEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFUnordEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFOrdNotEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFOrdNotEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFUnordNotEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFUnordNotEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFOrdLessThan(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFOrdLessThan, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFUnordLessThan(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFUnordLessThan, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFOrdGreaterThan(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFOrdGreaterThan, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFUnordGreaterThan(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFUnordGreaterThan, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFOrdLessThanEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFOrdLessThanEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFUnordLessThanEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFUnordLessThanEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFOrdGreaterThanEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFOrdGreaterThanEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFUnordGreaterThanEqual(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFUnordGreaterThanEqual, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpConvertFToU(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpConvertFToU, result_type} << operand << EndOp{};
}

Id Module::OpConvertFToS(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpConvertFToS, result_type} << operand << EndOp{};
}

Id Module::OpConvertSToF(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpConvertSToF, result_type} << operand << EndOp{};
}

Id Module::OpConvertUToF(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpConvertUToF, result_type} << operand << EndOp{};
}

Id Module::OpConvertUToPtr(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpConvertUToPtr, result_type} << operand << EndOp{};
}

Id Module::OpConvertPtrToU(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpConvertPtrToU, result_type} << operand << EndOp{};
}

Id Module::OpUConvert(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpUConvert, result_type} << operand << EndOp{};
}

Id Module::OpSConvert(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpSConvert, result_type} << operand << EndOp{};
}

Id Module::OpFConvert(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpFConvert, result_type} << operand << EndOp{};
}

Id Module::OpQuantizeToF16(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpQuantizeToF16, result_type} << operand << EndOp{};
}

Id Module::OpBitcast(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpBitcast, result_type} << operand << EndOp{};
}

Id Module::OpShiftRightLogical(Id result_type, Id base, Id shift) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpShiftRightLogical, result_type} << base << shift << EndOp{};
}

Id Module::OpShiftRightArithmetic(Id result_type, Id base, Id shift) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpShiftRightArithmetic, result_type} << base << shift << EndOp{};
}

Id Module::OpShiftLeftLogical(Id result_type, Id base, Id shift) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpShiftLeftLogical, result_type} << base << shift << EndOp{};
}

Id Module::OpBitwiseOr(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpBitwiseOr, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpBitwiseXor(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpBitwiseXor, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpBitwiseAnd(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpBitwiseAnd, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpNot(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpNot, result_type} << operand << EndOp{};
}

Id Module::OpBitFieldInsert(Id result_type, Id base, Id insert, Id offset, Id count) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpBitFieldInsert, result_type} << base << insert << offset << count << EndOp{};
}

Id Module::OpBitFieldSExtract(Id result_type, Id base, Id offset, Id count) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpBitFieldSExtract, result_type} << base << offset << count << EndOp{};
}

Id Module::OpBitFieldUExtract(Id result_type, Id base, Id offset, Id count) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpBitFieldUExtract, result_type} << base << offset << count << EndOp{};
}

Id Module::OpBitReverse(Id result_type, Id base) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpBitReverse, result_type} << base << EndOp{};
}

Id Module::OpBitCount(Id result_type, Id base) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpBitCount, result_type} << base << EndOp{};
}

Id Module::OpSNegate(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpSNegate, result_type} << operand << EndOp{};
}

Id Module::OpFNegate(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpFNegate, result_type} << operand << EndOp{};
}

Id Module::OpIAdd(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpIAdd, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFAdd(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFAdd, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpISub(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpISub, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFSub(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFSub, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpIMul(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpIMul, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpUMulExtended(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpUMulExtended, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpSMulExtended(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpSMulExtended, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFMul(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFMul, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpUDiv(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpUDiv, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpSDiv(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpSDiv, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFDiv(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFDiv, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpUMod(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpUMod, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpSMod(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpSMod, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFMod(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFMod, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpSRem(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpSRem, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpFRem(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpFRem, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpIAddCarry(Id result_type, Id operand_1, Id operand_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpIAddCarry, result_type} << operand_1 << operand_2 << EndOp{};
}

Id Module::OpVectorTimesScalar(Id result_type, Id vector, Id scalar) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpVectorTimesScalar, result_type} << vector << scalar << EndOp{};
}

Id Module::OpDot(Id result_type, Id vector_1, Id vector_2) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpDot, result_type} << vector_1 << vector_2 << EndOp{};
}

Id Module::OpExtInst(Id result_type, Id set, std::uint32_t instruction, std::span<const Id> operands) {
    code->Reserve(5 + operands.size());
    return *code << OpId{spv::Op::OpExtInst, result_type} << set << instruction << operands << EndOp{};
}

Id Module::OpFAbs(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450FAbs, x);
}

Id Module::OpSAbs(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450SAbs, x);
}

Id Module::OpRound(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Round, x);
}

Id Module::OpRoundEven(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450RoundEven, x);
}

Id Module::OpTrunc(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Trunc, x);
}

Id Module::OpFSign(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450FSign, x);
}

Id Module::OpSSign(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450SSign, x);
}

Id Module::OpFloor(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Floor, x);
}

Id Module::OpCeil(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Ceil, x);
}

Id Module::OpFract(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Fract, x);
}

Id Module::OpSin(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Sin, x);
}

Id Module::OpCos(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Cos, x);
}

Id Module::OpAsin(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Asin, x);
}

Id Module::OpAcos(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Acos, x);
}

Id Module::OpPow(Id result_type, Id x, Id y) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Pow, x, y);
}

Id Module::OpExp(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Exp, x);
}

Id Module::OpLog(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Log, x);
}

Id Module::OpExp2(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Exp2, x);
}

Id Module::OpLog2(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Log2, x);
}

Id Module::OpSqrt(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Sqrt, x);
}

Id Module::OpInverseSqrt(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450InverseSqrt, x);
}

Id Module::OpLdexp(Id result_type, Id x, Id exp) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Ldexp, x, exp);
}

Id Module::OpFMin(Id result_type, Id x, Id y) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450FMin, x, y);
}

Id Module::OpUMin(Id result_type, Id x, Id y) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450UMin, x, y);
}

Id Module::OpSMin(Id result_type, Id x, Id y) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450SMin, x, y);
}

Id Module::OpNMin(Id result_type, Id x, Id y) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450NMin, x, y);
}

Id Module::OpFMax(Id result_type, Id x, Id y) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450FMax, x, y);
}

Id Module::OpUMax(Id result_type, Id x, Id y) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450UMax, x, y);
}

Id Module::OpSMax(Id result_type, Id x, Id y) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450SMax, x, y);
}

Id Module::OpNMax(Id result_type, Id x, Id y) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450NMax, x, y);
}

Id Module::OpFClamp(Id result_type, Id x, Id min_val, Id max_val) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450FClamp, x, min_val, max_val);
}

Id Module::OpUClamp(Id result_type, Id x, Id min_val, Id max_val) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450UClamp, x, min_val, max_val);
}

Id Module::OpSClamp(Id result_type, Id x, Id min_val, Id max_val) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450SClamp, x, min_val, max_val);
}

Id Module::OpFma(Id result_type, Id a, Id b, Id c) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Fma, a, b, c);
}

Id Module::OpFrexpStruct(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450FrexpStruct, x);
}

Id Module::OpPackHalf2x16(Id result_type, Id v) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450PackHalf2x16, v);
}

Id Module::OpUnpackHalf2x16(Id result_type, Id v) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450UnpackHalf2x16, v);
}

Id Module::OpPackUnorm2x16(Id result_type, Id v) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450PackUnorm2x16, v);
}

Id Module::OpUnpackUnorm2x16(Id result_type, Id v) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450UnpackUnorm2x16, v);
}

Id Module::OpPackSnorm2x16(Id result_type, Id v) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450PackSnorm2x16, v);
}

Id Module::OpUnpackSnorm2x16(Id result_type, Id v) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450UnpackSnorm2x16, v);
}

Id Module::OpPackUnorm4x8(Id result_type, Id v) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450PackUnorm4x8, v);
}

Id Module::OpUnpackUnorm4x8(Id result_type, Id v) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450UnpackUnorm4x8, v);
}

Id Module::OpPackSnorm4x8(Id result_type, Id v) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450PackSnorm4x8, v);
}

Id Module::OpUnpackSnorm4x8(Id result_type, Id v) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450UnpackSnorm4x8, v);
}

Id Module::OpFindILsb(Id result_type, Id value) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450FindILsb, value);
}

Id Module::OpFindSMsb(Id result_type, Id value) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450FindSMsb, value);
}

Id Module::OpFindUMsb(Id result_type, Id value) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450FindUMsb, value);
}

Id Module::OpInterpolateAtCentroid(Id result_type, Id interpolant) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450InterpolateAtCentroid, interpolant);
}

Id Module::OpInterpolateAtSample(Id result_type, Id interpolant, Id sample) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450InterpolateAtSample, interpolant, sample);
}

Id Module::OpInterpolateAtOffset(Id result_type, Id interpolant, Id offset) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450InterpolateAtOffset, interpolant, offset);
}

Id Module::OpNormalize(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Normalize, x);
}

Id Module::OpCross(Id result_type, Id x, Id y) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Cross, x, y);
}

Id Module::OpLength(Id result_type, Id x) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450Length, x);
}

Id Module::OpFMix(Id result_type, Id x, Id y, Id a) {
    return OpExtInst(result_type, GetGLSLstd450(), GLSLstd450FMix, x, y, a);
}

Id Module::OpCubeFaceCoordAMD(Id result_type, Id cube_coord) {
    return OpExtInst(result_type, GetAmdGcnShader(), AMD_gcn_shaderCubeFaceCoordAMD, cube_coord);
}

Id Module::OpCubeFaceIndexAMD(Id result_type, Id cube_coord) {
    return OpExtInst(result_type, GetAmdGcnShader(), AMD_gcn_shaderCubeFaceIndexAMD, cube_coord);
}

Id Module::OpTimeAMD(Id result_type) {
    return OpExtInst(result_type, GetAmdGcnShader(), AMD_gcn_shaderTimeAMD);
}

Id Module::OpFMin3AMD(Id result_type, Id x, Id y, Id z) {
    return OpExtInst(result_type, GetAmdShaderTrinaryMinMax(), AMD_shader_trinary_minmaxFMin3AMD, x, y, z);
}

Id Module::OpUMin3AMD(Id result_type, Id x, Id y, Id z) {
    return OpExtInst(result_type, GetAmdShaderTrinaryMinMax(), AMD_shader_trinary_minmaxUMin3AMD, x, y, z);
}

Id Module::OpSMin3AMD(Id result_type, Id x, Id y, Id z) {
    return OpExtInst(result_type, GetAmdShaderTrinaryMinMax(), AMD_shader_trinary_minmaxSMin3AMD, x, y, z);
}

Id Module::OpFMax3AMD(Id result_type, Id x, Id y, Id z) {
    return OpExtInst(result_type, GetAmdShaderTrinaryMinMax(), AMD_shader_trinary_minmaxFMax3AMD, x, y, z);
}

Id Module::OpUMax3AMD(Id result_type, Id x, Id y, Id z) {
    return OpExtInst(result_type, GetAmdShaderTrinaryMinMax(), AMD_shader_trinary_minmaxUMax3AMD, x, y, z);
}

Id Module::OpSMax3AMD(Id result_type, Id x, Id y, Id z) {
    return OpExtInst(result_type, GetAmdShaderTrinaryMinMax(), AMD_shader_trinary_minmaxSMax3AMD, x, y, z);
}

Id Module::OpFMid3AMD(Id result_type, Id x, Id y, Id z) {
    return OpExtInst(result_type, GetAmdShaderTrinaryMinMax(), AMD_shader_trinary_minmaxFMid3AMD, x, y, z);
}

Id Module::OpUMid3AMD(Id result_type, Id x, Id y, Id z) {
    return OpExtInst(result_type, GetAmdShaderTrinaryMinMax(), AMD_shader_trinary_minmaxUMid3AMD, x, y, z);
}

Id Module::OpSMid3AMD(Id result_type, Id x, Id y, Id z) {
    return OpExtInst(result_type, GetAmdShaderTrinaryMinMax(), AMD_shader_trinary_minmaxSMid3AMD, x, y, z);
}

Id Module::OpInterpolateAtVertexAMD(Id result_type, Id interpolant, Id vertex_idx) {
    return OpExtInst(result_type, GetAmdExplicitVertexParameter(), AMD_shader_explicit_vertex_parameterInterpolateAtVertexAMD, interpolant, vertex_idx);
}

Id Module::OpDPdx(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpDPdx, result_type} << operand << EndOp{};
}

Id Module::OpDPdy(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpDPdy, result_type} << operand << EndOp{};
}

Id Module::OpFwidth(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpFwidth, result_type} << operand << EndOp{};
}

Id Module::OpDPdxFine(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpDPdxFine, result_type} << operand << EndOp{};
}

Id Module::OpDPdyFine(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpDPdyFine, result_type} << operand << EndOp{};
}

Id Module::OpFwidthFine(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpFwidthFine, result_type} << operand << EndOp{};
}

Id Module::OpDPdxCoarse(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpDPdxCoarse, result_type} << operand << EndOp{};
}

Id Module::OpDPdyCoarse(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpDPdyCoarse, result_type} << operand << EndOp{};
}

Id Module::OpFwidthCoarse(Id result_type, Id operand) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpFwidthCoarse, result_type} << operand << EndOp{};
}

Id Module::OpSampledImage(Id result_type, Id image, Id sampler) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpSampledImage, result_type} << image << sampler << EndOp{};
}

Id Module::OpImageSampleImplicitLod(Id result_type, Id sampled_image, Id coordinate, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(5 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageSampleImplicitLod, result_type} << sampled_image << coordinate << image_operands << operands << EndOp{};
}

Id Module::OpImageSampleExplicitLod(Id result_type, Id sampled_image, Id coordinate, spv::ImageOperandsMask image_operands, std::span<const Id> operands) {
    code->Reserve(6 + operands.size());
    return *code << OpId{spv::Op::OpImageSampleExplicitLod, result_type} << sampled_image << coordinate << image_operands << operands << EndOp{};
}

Id Module::OpImageSampleDrefImplicitLod(Id result_type, Id sampled_image, Id coordinate, Id dref, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(6 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageSampleDrefImplicitLod, result_type} << sampled_image << coordinate << dref << image_operands << operands << EndOp{};
}

Id Module::OpImageSampleDrefExplicitLod(Id result_type, Id sampled_image, Id coordinate, Id dref, spv::ImageOperandsMask image_operands, std::span<const Id> operands) {
    code->Reserve(7 + operands.size());
    return *code << OpId{spv::Op::OpImageSampleDrefExplicitLod, result_type} << sampled_image << coordinate << dref << image_operands << operands << EndOp{};
}

Id Module::OpImageSampleProjImplicitLod(Id result_type, Id sampled_image, Id coordinate, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(5 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageSampleProjImplicitLod, result_type} << sampled_image << coordinate << image_operands << operands << EndOp{};
}

Id Module::OpImageSampleProjExplicitLod(Id result_type, Id sampled_image, Id coordinate, spv::ImageOperandsMask image_operands, std::span<const Id> operands) {
    code->Reserve(6 + operands.size());
    return *code << OpId{spv::Op::OpImageSampleProjExplicitLod, result_type} << sampled_image << coordinate << image_operands << operands << EndOp{};
}

Id Module::OpImageSampleProjDrefImplicitLod(Id result_type, Id sampled_image, Id coordinate, Id dref, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(6 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageSampleProjDrefImplicitLod, result_type} << sampled_image << coordinate << dref << image_operands << operands << EndOp{};
}

Id Module::OpImageSampleProjDrefExplicitLod(Id result_type, Id sampled_image, Id coordinate, Id dref, spv::ImageOperandsMask image_operands, std::span<const Id> operands) {
    code->Reserve(7 + operands.size());
    return *code << OpId{spv::Op::OpImageSampleProjDrefExplicitLod, result_type} << sampled_image << coordinate << dref << image_operands << operands << EndOp{};
}

Id Module::OpImageFetch(Id result_type, Id sampled_image, Id coordinate, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(5 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageFetch, result_type} << sampled_image << coordinate << image_operands << operands << EndOp{};
}

Id Module::OpImageGather(Id result_type, Id sampled_image, Id coordinate, Id component, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(6 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageGather, result_type} << sampled_image << coordinate << component << image_operands << operands << EndOp{};
}

Id Module::OpImageDrefGather(Id result_type, Id sampled_image, Id coordinate, Id dref, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(6 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageDrefGather, result_type} << sampled_image << coordinate << dref << image_operands << operands << EndOp{};
}

Id Module::OpImageRead(Id result_type, Id sampled_image, Id coordinate, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(5 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageRead, result_type} << sampled_image << coordinate << image_operands << operands << EndOp{};
}

Id Module::OpImageWrite(Id image, Id coordinate, Id texel, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(4 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << spv::Op::OpImageWrite << image << coordinate << texel << image_operands << operands << EndOp{};
}

Id Module::OpImage(Id result_type, Id sampled_image) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpImage, result_type} << sampled_image << EndOp{};
}

Id Module::OpImageQuerySizeLod(Id result_type, Id image, Id level_of_detail) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpImageQuerySizeLod, result_type} << image << level_of_detail << EndOp{};
}

Id Module::OpImageQuerySize(Id result_type, Id image) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpImageQuerySize, result_type} << image << EndOp{};
}

Id Module::OpImageQueryLod(Id result_type, Id image, Id coordinate) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpImageQueryLod, result_type} << image << coordinate << EndOp{};
}

Id Module::OpImageQueryLevels(Id result_type, Id image) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpImageQueryLevels, result_type} << image << EndOp{};
}

Id Module::OpImageQuerySamples(Id result_type, Id image) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpImageQuerySamples, result_type} << image << EndOp{};
}

Id Module::OpImageSparseSampleImplicitLod(Id result_type, Id sampled_image, Id coordinate, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(5 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageSparseSampleImplicitLod, result_type} << sampled_image << coordinate << image_operands << operands << EndOp{};
}

Id Module::OpImageSparseSampleExplicitLod(Id result_type, Id sampled_image, Id coordinate, spv::ImageOperandsMask image_operands, std::span<const Id> operands) {
    code->Reserve(6 + operands.size());
    return *code << OpId{spv::Op::OpImageSparseSampleExplicitLod, result_type} << sampled_image << coordinate << image_operands << operands << EndOp{};
}

Id Module::OpImageSparseSampleDrefImplicitLod(Id result_type, Id sampled_image, Id coordinate, Id dref, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(6 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageSparseSampleDrefImplicitLod, result_type} << sampled_image << coordinate << dref << image_operands << operands << EndOp{};
}

Id Module::OpImageSparseSampleDrefExplicitLod(Id result_type, Id sampled_image, Id coordinate, Id dref, spv::ImageOperandsMask image_operands, std::span<const Id> operands) {
    code->Reserve(7 + operands.size());
    return *code << OpId{spv::Op::OpImageSparseSampleDrefExplicitLod, result_type} << sampled_image << coordinate << dref << image_operands << operands << EndOp{};
}

Id Module::OpImageSparseFetch(Id result_type, Id image, Id coordinate, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(5 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageSparseFetch, result_type} << image << coordinate << image_operands << operands << EndOp{};
}

Id Module::OpImageSparseGather(Id result_type, Id sampled_image, Id coordinate, Id component, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(6 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageSparseGather, result_type} << sampled_image << coordinate << component << image_operands << operands << EndOp{};
}

Id Module::OpImageSparseDrefGather(Id result_type, Id sampled_image, Id coordinate, Id dref, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(6 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageSparseDrefGather, result_type} << sampled_image << coordinate << dref << image_operands << operands << EndOp{};
}

Id Module::OpImageSparseTexelsResident(Id result_type, Id resident_code) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpImageSparseTexelsResident, result_type} << resident_code << EndOp{};
}

Id Module::OpImageSparseRead(Id result_type, Id image, Id coordinate, std::optional<spv::ImageOperandsMask> image_operands, std::span<const Id> operands) {
    code->Reserve(5 + (image_operands.has_value() ? 1 : 0) + operands.size());
    return *code << OpId{spv::Op::OpImageSparseRead, result_type} << image << coordinate << image_operands << operands << EndOp{};
}

Id Module::OpSubgroupBallotKHR(Id result_type, Id predicate) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpSubgroupBallotKHR, result_type} << predicate << EndOp{};
}

Id Module::OpSubgroupReadInvocationKHR(Id result_type, Id value, Id index) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpSubgroupReadInvocationKHR, result_type} << value << index << EndOp{};
}

Id Module::OpSubgroupAllKHR(Id result_type, Id predicate) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpSubgroupAllKHR, result_type} << predicate << EndOp{};
}

Id Module::OpSubgroupAnyKHR(Id result_type, Id predicate) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpSubgroupAnyKHR, result_type} << predicate << EndOp{};
}

Id Module::OpSubgroupAllEqualKHR(Id result_type, Id predicate) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpSubgroupAllEqualKHR, result_type} << predicate << EndOp{};
}

Id Module::OpGroupNonUniformBroadcast(Id result_type, Id scope, Id value, Id id) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpGroupNonUniformBroadcast, result_type} << scope << value << id << EndOp{};
}

Id Module::OpGroupNonUniformShuffle(Id result_type, Id scope, Id value, Id id) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpGroupNonUniformShuffle, result_type} << scope << value << id << EndOp{};
}

Id Module::OpGroupNonUniformShuffleXor(Id result_type, Id scope, Id value, Id mask) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpGroupNonUniformShuffleXor, result_type} << scope << value << mask << EndOp{};
}

Id Module::OpGroupNonUniformAll(Id result_type, Id scope, Id predicate) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpGroupNonUniformAll, result_type} << scope << predicate << EndOp{};
}

Id Module::OpGroupNonUniformAny(Id result_type, Id scope, Id predicate) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpGroupNonUniformAny, result_type} << scope << predicate << EndOp{};
}

Id Module::OpGroupNonUniformAllEqual(Id result_type, Id scope, Id value) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpGroupNonUniformAllEqual, result_type} << scope << value << EndOp{};
}

Id Module::OpGroupNonUniformBallot(Id result_type, Id scope, Id predicate) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpGroupNonUniformBallot, result_type} << scope << predicate << EndOp{};
}

Id Module::OpGroupNonUniformBroadcastFirst(Id result_type, Id scope, Id value) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpGroupNonUniformBroadcastFirst, result_type} << scope << value << EndOp{};
}

Id Module::OpGroupNonUniformElect(Id result_type, Id scope) {
    code->Reserve(4);
    return *code << OpId{spv::Op::OpGroupNonUniformElect, result_type} << scope << EndOp{};
}

Id Module::OpGroupNonUniformInverseBallot(Id result_type, Id scope, Id value) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpGroupNonUniformInverseBallot, result_type} << scope << value << EndOp{};
}

Id Module::OpGroupNonUniformBallotBitCount(Id result_type, Id scope, spv::GroupOperation group_op, Id value) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpGroupNonUniformBallotBitCount, result_type} << scope << group_op << value << EndOp{};
}

Id Module::OpGroupNonUniformBallotFindLSB(Id result_type, Id scope, Id value) {
    code->Reserve(5);
    return *code << OpId{spv::Op::OpGroupNonUniformBallotFindLSB, result_type} << scope << value << EndOp{};
}

Id Module::OpGroupNonUniformQuadBroadcast(Id result_type, Id scope, Id value, Id index) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpGroupNonUniformQuadBroadcast, result_type} << scope << value << index << EndOp{};
}

Id Module::OpAtomicLoad(Id result_type, Id pointer, Id memory, Id semantics) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpAtomicLoad, result_type} << pointer << memory << semantics << EndOp{};
}

Id Module::OpAtomicStore(Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(5);
    return *code << spv::Op::OpAtomicStore << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicExchange(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicExchange, result_type} << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicCompareExchange(Id result_type, Id pointer, Id memory, Id equal, Id unequal, Id value, Id comparator) {
    code->Reserve(9);
    return *code << OpId{spv::Op::OpAtomicCompareExchange, result_type} << pointer << memory << equal << unequal << value << comparator << EndOp{};
}

Id Module::OpAtomicIIncrement(Id result_type, Id pointer, Id memory, Id semantics) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpAtomicIIncrement, result_type} << pointer << memory << semantics << EndOp{};
}

Id Module::OpAtomicIDecrement(Id result_type, Id pointer, Id memory, Id semantics) {
    code->Reserve(6);
    return *code << OpId{spv::Op::OpAtomicIDecrement, result_type} << pointer << memory << semantics << EndOp{};
}

Id Module::OpAtomicIAdd(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicIAdd, result_type} << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicISub(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicISub, result_type} << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicSMin(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicSMin, result_type} << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicUMin(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicUMin, result_type} << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicSMax(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicSMax, result_type} << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicUMax(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicUMax, result_type} << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicFMax(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicFMaxEXT, result_type} << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicFMin(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicFMinEXT, result_type} << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicAnd(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicAnd, result_type} << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicOr(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicOr, result_type} << pointer << memory << semantics << value << EndOp{};
}

Id Module::OpAtomicXor(Id result_type, Id pointer, Id memory, Id semantics, Id value) {
    code->Reserve(7);
    return *code << OpId{spv::Op::OpAtomicXor, result_type} << pointer << memory << semantics << value << EndOp{};
}

} // namespace Sirit
